version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
    # Check for updates to node modules every weekday
      interval: 'daily'
    allow:
      - dependency-type: 'direct'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: 'daily'
